# Generated by Django 4.0.4 on 2022-06-03 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cate_ser',
            fields=[
                ('id_cate', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_ser', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado_ser', models.CharField(default='--', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehi', models.AutoField(primary_key=True, serialize=False)),
                ('cate_vehi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_ser', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ser', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_ser', models.IntegerField()),
                ('categoria_ser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carWash.cate_ser')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato_ser',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ini', models.DateField()),
                ('dueno', models.CharField(default='--', max_length=45)),
                ('estado_es', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carWash.estado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carWash.servicios')),
                ('vehi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carWash.vehiculo')),
            ],
        ),
    ]
