# Generated by Django 4.0.4 on 2022-06-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carWash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estado_ser',
            field=models.CharField(max_length=50),
        ),
    ]
