from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', index, name="IND"),
    path('registrar/', registrar, name="REG"),
    path('iniciar/', iniciar, name="INI"),
    path('servicios/', servicios, name="SER"),
    path('agregar_ser/', agregar_ser, name="AGRE_SERV"),
    path('agenda_cli/', agenda_cli, name="AGE_CLI"),
    path('agenda_ad/', agenda_ad, name="AGE_AD"),
    path('form_agre_ser/', form_agre_ser, name="FORM_AGRE_SERV"),
    path('info_ser/<id>/', info_ser, name="INFO"),
    path('modificar/', modificar, name="MODI"),
    path('buscar_modificar/<id>/', buscar_modificar, name="BUSCARM"),
    path('cerrar_sesion/', cerrar_sesion, name="CERRAR_SESION"),
    path('eliminar/<id>/', eliminar, name="ELI"),
    path('insertar_contrato/', insertar_contrato, name="INSERTA"),
    path('cancelar_contrato/<id>/', cancelar_contrato, name="CANCE"),
    path('cancelar_contr_cli/<id>/', cancelar_contr_cli, name="CANCEC"),
    path('buscar_modificar_ad/<id>/', buscar_modificar_ad, name="BUSCARC"),
    path('modificar_c/', modificar_c, name="MODIC"),
    path('form_agre_cate/', form_agre_cate, name="FORM_AGRE_CATE"),
    path('form_agre_esta/', form_agre_esta, name="FORM_AGRE_ESTA"),
    path('cate_esta/', cate_esta, name="CATE_ESTA"),
    path('estado/', estado, name="ESTA"),
    path('eliminar_cate/<id>/', eliminar_cate, name="ELICATE"),
    path('eliminar_esta/<id>/', eliminar_esta, name="ELIESTA"),
    path('form_agre_auto/', form_agre_auto, name="FORM_AGRE_VEHI"),
    path('vehi/', vehi, name="VEHI"),
    path('eliminar_vehi/<id>/', eliminar_vehi, name="ELIVEHI"),
    path('index/', auth_views.LoginView.as_view(template_name='index.html', redirect_authenticated_user=True), name='index'),
    path('logout/', auth_views.LogoutView.as_view(next_page='index'), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('export_pdf/', export_pdf, name="PDF"),
    path('canchas/', export_csv, name='CANCHAS'),
    path('canchas_text', informe_text, name='CANCHASTXT'),
    path('canchas_csv', informe_csv, name='CANCHASCSV'),
]